Comment model and API creation
Magnico/myblog pull request #12
Opened 2023-03-30 19:07 UTC by Magnico

Changes made:
- Tests for the API endpoints and fields restrictions
- Created model Comment
- Created serializer for Comment GET and PATCH method
- Created serializer for comment POST method
- Endpoints `blog/api/comment` created

2023-03-30 22:00 UTC, ejariza-evowill commented on blog/models.py
> +    body = models.CharField(max_length=255,null=False,blank=False)
Why did you decide to make this change?

2023-03-30 22:00 UTC, ejariza-evowill commented on blog/tests.py
> +                Comment.objects.create(body=None, author=self.user, post=None).full_clean()
I think this last assertion is unnecessary because is already tested in the previous ones

2023-03-30 22:00 UTC, ejariza-evowill commented on blog/tests.py
> +        post = get_object_or_404(Post, title="testing")
You can keep using the ORM `get` method because if it throws an exception is because the functionality is not working correctly.

2023-03-30 22:12 UTC, Magnico commented on blog/models.py
> +    body = models.CharField(max_length=255,null=False,blank=False)
After doing the test for validation of the constraints in the Comment model I realized that when using the TextField with the max_length=255 the DataError that should appear when I put a string of length 256 wasn't raised.
I thought that was an error with the Comment model but when I modified the test for Post, I realized that it also didn't raise the DataError with the string.
After some search I found that the CharField is used for strings of a length of 255 maximum and the TextField is used for beyond that.

2023-03-30 23:55 UTC, Magnico commented on blog/models.py
> +    body = models.CharField(max_length=255,null=False,blank=False)
Here is the reference to the [Django documentation](https://docs.djangoproject.com/en/4.1/ref/models/fields/#textfield)

2023-03-31 16:28 UTC, ejariza-evowill commented on blog/models.py
> +    body = models.CharField(max_length=255,null=False,blank=False)
JFYTK, you could also use a [`MaxLengthValidator`](https://docs.djangoproject.com/en/4.1/ref/validators/#maxlengthvalidator) and test for ValidationError. But this is an ok solution too.

2023-03-31 16:37 UTC, ejariza-evowill requested changes

2023-03-31 16:37 UTC, ejariza-evowill commented on blog/tests.py
> -                Post.objects.create(title=None, body=None,author=testuser).full_clean()
I think the `post` assertions were right, what I meant is that you need to test individually for each non-nullable field, but after that the validation for all non-nullable fields set as `None` at the same time is redundant.

2023-03-31 18:51 UTC, Magnico commented on blog/tests.py
> -                Post.objects.create(title=None, body=None,author=testuser).full_clean()
Ok, then i will proceed to reset the changes from the post tests

2023-03-31 19:44 UTC, ejariza-evowill approved these changes

2023-03-31 19:46 UTC, merged