Comment and Post models new fields
Magnico/myblog pull request #13
Opened 2023-04-03 17:06 UTC by Magnico

Changes made:
- Field created_at added to Comment and Post model
- Fields comments_count, safe and img added to Post model
- Tests updated for new fields

2023-04-03 18:05 UTC, ejariza-evowill requested changes

2023-04-03 18:05 UTC, ejariza-evowill commented on blog/models.py
> +    img = models.ImageField(upload_to=get_upload_path,null=True,blank=True)
This is not necessary, as ImageField (or more specifically, its parent FileField) supports [strftime formatting.](https://docs.djangoproject.com/en/4.1/ref/models/fields/#filefield)

2023-04-03 18:05 UTC, ejariza-evowill commented on blog/models.py
> +                original.img.delete(save=False)
Why do you consider it's necessary to do this?

2023-04-03 18:05 UTC, ejariza-evowill commented on blog/tests.py
> +        self.assertEqual(post.img.name, response.data['img'] if response.data['img'] else '')
Why the conditional here? shouldn't the test expect always the same results?

2023-04-03 19:07 UTC, Magnico commented on blog/models.py
> +                original.img.delete(save=False)
when I was testing the functionality of uploading images through the django administrator, I saw that when deleting or changing an image in the post the image itself remained saved in the corresponding directory.

2023-04-03 19:28 UTC, Magnico commented on blog/tests.py
> +        self.assertEqual(post.img.name, response.data['img'] if response.data['img'] else '')
Happens that when there is no image attached, the response have `None` in the `response.data['img']` and the `post.img.name` would be `''` so I use the conditional for that case.

2023-04-03 20:09 UTC, ejariza-evowill commented on blog/models.py
> +                original.img.delete(save=False)
Oh, ok, I didn't specify to delete images, but it still is a sensible decision, so it's ok.

2023-04-03 20:11 UTC, ejariza-evowill commented on blog/tests.py
> +        self.assertEqual(post.img.name, response.data['img'] if response.data['img'] else '')
But if in the test the logic is well isolated it should happen only one of both cases.

2023-04-03 20:23 UTC, Magnico commented on blog/tests.py
> +        self.assertEqual(post.img.name, response.data['img'] if response.data['img'] else '')
Yes, i understand now what you mean. I am correcting the test.

2023-04-03 22:22 UTC, Magnico commented
Corrections made.

2023-04-04 16:53 UTC, ejariza-evowill approved these changes

2023-04-04 16:53 UTC, ejariza-evowill commented on blog/tests.py
> +        expected_path = f'uploads/images/{post.created_at.strftime("%Y/%m/%d")}/test_update_2.jpg'
Good addition, strftime ins a great help here.

2023-04-05 14:03 UTC, merged