UserTag intermediate model
Magnico/myblog pull request #15
Opened 2023-04-12 21:07 UTC by Magnico

Changes made:
- Created model UserTag
- Created endpoints for tagging a user, retrieving the tagged users and posts.
- Tests for endpoints created

2023-04-13 17:02 UTC, ejariza-evowill requested changes

2023-04-13 17:02 UTC, ejariza-evowill commented on blog/models.py
> +        return self.usertag_set.last().created_at if self.usertag_set.last() else None
By truthy value, I think that you can use the `self.usertag_set` without the `last()` as well, but this is ok.``

2023-04-13 17:02 UTC, ejariza-evowill commented on blog/tests.py
> +            UserTag.objects.create(user=user, post=post)
I would refactor these tests into a new class, so all the tags and post creation can be done only once at the `__init__` method.

2023-04-13 17:38 UTC, Magnico commented on blog/tests.py
> +            UserTag.objects.create(user=user, post=post)
to confirm, what you mean is to separate the tests test_post_tagged_count and test_post_last_tag_date in another class apart from PostTestCase, and use __init__ to create the user tags to be used in the two tests?

2023-04-14 21:52 UTC, ejariza-evowill approved these changes

2023-04-14 21:52 UTC, ejariza-evowill commented on blog/tests.py
> +            UserTag.objects.create(user=user, post=post)
yes, so you keep DRY and not have to repeat the process of setting up. But thinking about this I think is most appropriated to use the [setup method](https://docs.djangoproject.com/en/4.1/topics/testing/overview/#writing-tests) for this.

2023-04-14 22:21 UTC, Magnico commented
Changes made:
- Created test class UserTagTestCase

2023-04-14 22:37 UTC, ejariza-evowill approved these changes

2023-04-14 23:06 UTC, merged