Installation an migration of blog app
Magnico/myblog pull request #3
Opened 2023-03-07 21:25 UTC by Magnico

2023-03-07 23:21 UTC, ejariza-evowill requested changes
Please check the conflicts that are appearing for this merge request.

2023-03-08 13:56 UTC, Magnico commented
The conflict was within the index of /blog route. Fixed by accepting the incoming changes.

2023-03-08 16:52 UTC, ejariza-evowill approved these changes

2023-03-08 16:52 UTC, ejariza-evowill commented on myblog/settings.py
> +INSTALLED_APPS = THIRD_APPS + LOCAL_APPS + DJANGO_APPS
This is a very smart way of organizing apps, actually.

2023-03-08 16:52 UTC, merged