Feature tests
Magnico/myblog pull request #4
Opened 2023-03-11 23:04 UTC by Magnico

2023-03-13 14:08 UTC, ejariza-evowill requested changes
Please point your changes to the `develop` branch instead of the `main` branch.

2023-03-13 14:19 UTC, Magnico commented
Change made.

2023-03-13 14:44 UTC, ejariza-evowill requested changes

2023-03-13 14:44 UTC, ejariza-evowill commented on blog/tests.py
> +            Post.objects.create(title=None, body="test2",author=None).full_clean()
Consider this: if Post does not allow `null` `title`, but allows `null` `body`, the test will pass, because only depends on one of these four lines to raise an IntegrityError to pass. Please address this issue.

2023-03-13 14:44 UTC, ejariza-evowill commented on blog/tests.py
> +            Post.objects.create(title="", body="test2",author=testuser).full_clean()
The same story as with the previous comment, you need to check it raises error for each line separately.

2023-03-13 22:47 UTC, Magnico commented
Changes made, waiting for review

2023-03-14 14:41 UTC, ejariza-evowill approved these changes

2023-03-17 19:57 UTC, merged