Created test for sign up, log in and log out
Magnico/myblog pull request #6
Opened 2023-03-18 03:41 UTC by Magnico

Created tests for user creation, login and logout through the client

2023-03-19 16:10 UTC, ejariza-evowill requested changes

2023-03-19 16:10 UTC, ejariza-evowill commented on blog/tests.py
> +        self.assertEquals(User.objects.count(), 1)
Why are you asserting this here if in this test we are assuming that user already exists?

2023-03-19 16:10 UTC, ejariza-evowill commented on blog/tests.py
> +        self.assertFalse(self.client.session.get('_auth_user_id'))
For both assertions of logged in and logged out is more clear to use `assertIsNone()` and `assertIsNotNone()` because that's exactly what we want to verify.

2023-03-19 23:39 UTC, Magnico commented
Changes made:

- Changed assertFalse and assertTrue for assertIsNone and assertIsNotNone
- Removed some unnecessary code

2023-03-20 14:28 UTC, ejariza-evowill approved these changes

2023-03-20 14:28 UTC, merged