API for posts creation
Magnico/myblog pull request #9
Opened 2023-03-23 20:27 UTC by Magnico

Changes made:
- In post serializer user field set to string representation
- API configured to require authentication 
- POST method implemented for post creation on /blog/api/post
- Test created for post creation (POST method)
- Test for post list edited and renamed to test_post_list (GET method)

2023-03-23 22:21 UTC, ejariza-evowill requested changes

2023-03-23 22:21 UTC, ejariza-evowill commented on blog/views.py
> +
This is somewhat redundant, because the `create` method from `CreateModelMixin` already implements this logic, and calls `perform_create`, in which you already implemented the method for creating the post with the authenticated user as author.

2023-03-23 22:52 UTC, Magnico commented
Redundant logic removed, it was an error regarding the inheritance of the `CreateModelMixin` class

2023-03-24 15:27 UTC, ejariza-evowill approved these changes

2023-03-24 17:29 UTC, merged